#!/usr/bin/env node

const fs = require('fs');
const hash = require('object-hash');
const path = require('path');

// argv[0] is probably a fully-qualified path to node, so don't hash it
const argv_hash = hash(process.argv.slice(1));
const logfile = path.resolve(__dirname, 'electron-fiddle-logs', argv_hash);

if (!fs.existsSync(logfile)) {
  const argv = JSON.stringify(process.argv);
  throw new Error(`No logfile found for ${argv_hash} ${argv}`);
}

console.log(fs.readFileSync(logfile, { encoding: 'utf8' }));
