name: tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # tag: v3.3.0
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c  # tag: v3.6.0
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn install
      - name: Build 
        run: yarn build
      - name: Run tests
        run: yarn test:ci
      - name: Coveralls
        uses: coverallsapp/github-action@9ba913c152ae4be1327bfb9085dc806cedb44057 # v1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

