name: tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn install
      - name: Build 
        run: yarn build
      - name: Run tests
        run: yarn test
