name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: 'yarn install'
      - name: Build 
        run: 'yarn build'
      - name: Run Probot Client tests
        run: yarn workspace @electron/bugbot-bot test
      - name: Run Broker tests
        run: yarn workspace @electron/bugbot-broker test
      - name: Run Runner tests
        run: yarn workspace @electron/bugbot-runner test

